---
# tasks file for ansible-role-docker-container-minio

- name: docker_image {{ docker_image_minio_name }} exists
  community.docker.docker_image_info:
    name: '{{ docker_image_minio_name }}'
  register: docker_image_minio_exist_result

- name: docker_image pull {{ docker_image_minio_name }}
  community.docker.docker_image:
    name: '{{ docker_image_minio_name }}'
    source: pull
    # Select platform for pulling. If not specified, will pull whatever docker prefers.
    pull:
      platform: amd64
  when: (docker_image_minio_pull is defined) or (docker_image_minio_exist_result.images | length == 0)

- name: docker_network {{ docker_container_minio_name }}
  community.docker.docker_network:
    name: "{{ docker_network_minio_name }}"
    driver: "{{ docker_network_minio_driver | default('bridge') }}"
    attachable: "{{ docker_network_minio_attachable | default('yes') }}"
    enable_ipv6: "{{ docker_network_minio_enable_ipv6 | default('no') }}"
    internal: "{{ docker_network_minio_internal | default('no') }}"
    state: present


- name: docker_container {{ docker_container_minio_name }}
  community.docker.docker_container:
    command: "{{ docker_container_minio_command | default(omit) }}"
    name: "{{ docker_container_minio_name }}"
    image: "{{ docker_container_minio_image }}"
    state: "{{ docker_container_minio_state | default('started') }}"
    recreate: "{{ docker_container_minio_recreate | default('no') }}"
    restart: "{{ docker_container_minio_restart | default('no') }}"
    restart_policy: "{{ docker_container_minio_restart_policy | default('always') }}"
    container_default_behavior: no_defaults
    auto_remove: "{{ docker_container_minio_auto_remove | default('no') }}"
    detach: "{{ docker_container_minio_detach | default('yes') }}"
    init: "{{ docker_container_minio_init | default('no') }}"
    interactive: "{{ docker_container_minio_interactive | default('no') }}"
    keep_volumes: "{{ docker_container_minio_keep_volumes | default('yes') }}"
    memory: "{{ docker_container_minio_memory | default('0') }}"
    paused: "{{ docker_container_minio_paused | default('no') }}"
    privileged: "{{ docker_container_minio_privileged | default('no') }}"
    read_only: "{{ docker_container_minio_read_only | default('no') }}"
    tty: "{{ docker_container_minio_tty | default('no') }}"
    env_file: "{{ docker_container_minio_env_file | default(omit) }}"
    env: "{{ docker_container_minio_env | default(omit) }}"
    volumes: "{{ docker_container_minio_volumes | default(omit) }}"
    labels: "{{ docker_container_minio_labels | default(omit) }}"
    networks_cli_compatible: "{{ docker_container_minio_networks_cli_compatible | default('yes') }}"
    network_mode: "{{ docker_network_minio_name }}"
    pull: "{{ docker_container_minio_pull | default('no') }}"
    purge_networks: "{{ docker_container_minio_purge_networks | default('yes') }}"
    networks: "{{ docker_container_minio_networks }}"
    published_ports: "{{ docker_container_minio_ports | default(omit) }}"
